# Created using wingetcreate 1.10.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: LeoKlaus.HeadsetControl-GUI
PackageVersion: 0.19.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: HeadsetControl-GUI.exe
  PortableCommandAlias: HeadsetControl-GUI
UpgradeBehavior: uninstallPrevious
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
    MinimumVersion: 14.32.31332.0
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/LeoKlaus/HeadsetControl-GUI/releases/download/0.19.3/HeadsetControl-GUI_windows_x64.zip
  InstallerSha256: EBF5432011760C8CCB5D096659EF1720EC3864FD1C5F71640911BEF2B325B99F
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2025-07-22
